# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\SocialNetworkSimulator\UI\CityDiffusion.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CityDiffusionWindow(object):
    def setupUi(self, CityDiffusionWindow):
        CityDiffusionWindow.setObjectName(_fromUtf8("CityDiffusionWindow"))
        CityDiffusionWindow.resize(1094, 866)
        self.centralwidget = QtGui.QWidget(CityDiffusionWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(256, 16777215))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.labelSelectBaseMap = QtGui.QLabel(self.groupBox)
        self.labelSelectBaseMap.setGeometry(QtCore.QRect(19, 28, 181, 16))
        self.labelSelectBaseMap.setObjectName(_fromUtf8("labelSelectBaseMap"))
        self.pushButtonSelectBaseMap = QtGui.QPushButton(self.groupBox)
        self.pushButtonSelectBaseMap.setGeometry(QtCore.QRect(173, 49, 71, 23))
        self.pushButtonSelectBaseMap.setObjectName(_fromUtf8("pushButtonSelectBaseMap"))
        self.lineEditPathName = QtGui.QLineEdit(self.groupBox)
        self.lineEditPathName.setGeometry(QtCore.QRect(20, 50, 151, 21))
        self.lineEditPathName.setObjectName(_fromUtf8("lineEditPathName"))
        self.pushButtonOpenNetwork = QtGui.QPushButton(self.groupBox)
        self.pushButtonOpenNetwork.setGeometry(QtCore.QRect(20, 74, 151, 23))
        self.pushButtonOpenNetwork.setObjectName(_fromUtf8("pushButtonOpenNetwork"))
        self.pushButtonWeightMatrix = QtGui.QPushButton(self.groupBox)
        self.pushButtonWeightMatrix.setGeometry(QtCore.QRect(20, 100, 151, 23))
        self.pushButtonWeightMatrix.setObjectName(_fromUtf8("pushButtonWeightMatrix"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 129, 61, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButtonDiffusion = QtGui.QPushButton(self.groupBox)
        self.pushButtonDiffusion.setGeometry(QtCore.QRect(160, 690, 81, 23))
        self.pushButtonDiffusion.setObjectName(_fromUtf8("pushButtonDiffusion"))
        self.textEditSeedNodes = QtGui.QTextEdit(self.groupBox)
        self.textEditSeedNodes.setGeometry(QtCore.QRect(20, 149, 221, 51))
        self.textEditSeedNodes.setObjectName(_fromUtf8("textEditSeedNodes"))
        self.tableWidgetEmergencyIndex = QtGui.QTableWidget(self.groupBox)
        self.tableWidgetEmergencyIndex.setGeometry(QtCore.QRect(20, 380, 221, 171))
        self.tableWidgetEmergencyIndex.setMinimumSize(QtCore.QSize(221, 0))
        self.tableWidgetEmergencyIndex.setObjectName(_fromUtf8("tableWidgetEmergencyIndex"))
        self.tableWidgetEmergencyIndex.setColumnCount(1)
        self.tableWidgetEmergencyIndex.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidgetEmergencyIndex.setHorizontalHeaderItem(0, item)
        self.pushButtonSetting = QtGui.QPushButton(self.groupBox)
        self.pushButtonSetting.setGeometry(QtCore.QRect(190, 350, 51, 23))
        self.pushButtonSetting.setObjectName(_fromUtf8("pushButtonSetting"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(20, 350, 111, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEditEmergencyIndexValue = QtGui.QLineEdit(self.groupBox)
        self.lineEditEmergencyIndexValue.setGeometry(QtCore.QRect(140, 350, 41, 20))
        self.lineEditEmergencyIndexValue.setObjectName(_fromUtf8("lineEditEmergencyIndexValue"))
        self.pushButtonDifferentValue = QtGui.QPushButton(self.groupBox)
        self.pushButtonDifferentValue.setGeometry(QtCore.QRect(20, 320, 161, 23))
        self.pushButtonDifferentValue.setObjectName(_fromUtf8("pushButtonDifferentValue"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 241, 201))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 220, 241, 71))
        self.groupBox_3.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.pushButtonClear = QtGui.QPushButton(self.groupBox)
        self.pushButtonClear.setGeometry(QtCore.QRect(190, 320, 51, 23))
        self.pushButtonClear.setObjectName(_fromUtf8("pushButtonClear"))
        self.lineEditStep = QtGui.QLineEdit(self.groupBox)
        self.lineEditStep.setGeometry(QtCore.QRect(140, 240, 101, 20))
        self.lineEditStep.setObjectName(_fromUtf8("lineEditStep"))
        self.radioButtonPercentage = QtGui.QRadioButton(self.groupBox)
        self.radioButtonPercentage.setGeometry(QtCore.QRect(20, 265, 161, 17))
        self.radioButtonPercentage.setObjectName(_fromUtf8("radioButtonPercentage"))
        self.lineEditPercentage = QtGui.QLineEdit(self.groupBox)
        self.lineEditPercentage.setGeometry(QtCore.QRect(180, 265, 61, 20))
        self.lineEditPercentage.setObjectName(_fromUtf8("lineEditPercentage"))
        self.radioButtonSteps = QtGui.QRadioButton(self.groupBox)
        self.radioButtonSteps.setGeometry(QtCore.QRect(20, 240, 121, 17))
        self.radioButtonSteps.setChecked(True)
        self.radioButtonSteps.setObjectName(_fromUtf8("radioButtonSteps"))
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 570, 241, 111))
        self.groupBox_4.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.lineEditDecayedRatio = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditDecayedRatio.setEnabled(False)
        self.lineEditDecayedRatio.setGeometry(QtCore.QRect(130, 76, 101, 20))
        self.lineEditDecayedRatio.setObjectName(_fromUtf8("lineEditDecayedRatio"))
        self.radioButtonRegional = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonRegional.setGeometry(QtCore.QRect(10, 30, 71, 17))
        self.radioButtonRegional.setObjectName(_fromUtf8("radioButtonRegional"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setEnabled(False)
        self.label_5.setGeometry(QtCore.QRect(26, 50, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.radioButtonGlobal = QtGui.QRadioButton(self.groupBox_4)
        self.radioButtonGlobal.setGeometry(QtCore.QRect(10, 10, 61, 17))
        self.radioButtonGlobal.setChecked(True)
        self.radioButtonGlobal.setObjectName(_fromUtf8("radioButtonGlobal"))
        self.lineEditDecayedRadius = QtGui.QLineEdit(self.groupBox_4)
        self.lineEditDecayedRadius.setEnabled(False)
        self.lineEditDecayedRadius.setGeometry(QtCore.QRect(130, 50, 101, 20))
        self.lineEditDecayedRadius.setObjectName(_fromUtf8("lineEditDecayedRadius"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setEnabled(False)
        self.label_6.setGeometry(QtCore.QRect(26, 77, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 300, 241, 261))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.groupBox_5.raise_()
        self.groupBox_3.raise_()
        self.tableWidgetEmergencyIndex.raise_()
        self.groupBox_2.raise_()
        self.labelSelectBaseMap.raise_()
        self.pushButtonSelectBaseMap.raise_()
        self.lineEditPathName.raise_()
        self.pushButtonOpenNetwork.raise_()
        self.pushButtonWeightMatrix.raise_()
        self.label.raise_()
        self.pushButtonDiffusion.raise_()
        self.textEditSeedNodes.raise_()
        self.pushButtonSetting.raise_()
        self.label_7.raise_()
        self.lineEditEmergencyIndexValue.raise_()
        self.pushButtonDifferentValue.raise_()
        self.pushButtonClear.raise_()
        self.lineEditStep.raise_()
        self.radioButtonPercentage.raise_()
        self.lineEditPercentage.raise_()
        self.radioButtonSteps.raise_()
        self.groupBox_4.raise_()
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBoxPreview = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreview.sizePolicy().hasHeightForWidth())
        self.groupBoxPreview.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(9)
        self.groupBoxPreview.setFont(font)
        self.groupBoxPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxPreview.setFlat(False)
        self.groupBoxPreview.setCheckable(False)
        self.groupBoxPreview.setObjectName(_fromUtf8("groupBoxPreview"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBoxPreview)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.FrameCanvas = QtGui.QWidget(self.groupBoxPreview)
        self.FrameCanvas.setEnabled(True)
        self.FrameCanvas.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.FrameCanvas.setObjectName(_fromUtf8("FrameCanvas"))
        self.gridLayout = QtGui.QGridLayout(self.FrameCanvas)
        self.gridLayout.setMargin(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2.addWidget(self.FrameCanvas)
        self.horizontalLayout.addWidget(self.groupBoxPreview)
        CityDiffusionWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(CityDiffusionWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        CityDiffusionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(CityDiffusionWindow)
        QtCore.QMetaObject.connectSlotsByName(CityDiffusionWindow)

    def retranslateUi(self, CityDiffusionWindow):
        CityDiffusionWindow.setWindowTitle(_translate("CityDiffusionWindow", "Informaiton Diffusion Among Cities", None))
        self.labelSelectBaseMap.setText(_translate("CityDiffusionWindow", "Please Select Base Map File", None))
        self.pushButtonSelectBaseMap.setText(_translate("CityDiffusionWindow", "Select", None))
        self.pushButtonOpenNetwork.setText(_translate("CityDiffusionWindow", "Load Network File", None))
        self.pushButtonWeightMatrix.setText(_translate("CityDiffusionWindow", "Load Weight Matrix File", None))
        self.label.setText(_translate("CityDiffusionWindow", "Source City", None))
        self.pushButtonDiffusion.setText(_translate("CityDiffusionWindow", "Diffusion", None))
        item = self.tableWidgetEmergencyIndex.horizontalHeaderItem(0)
        item.setText(_translate("CityDiffusionWindow", "Urgency Value", None))
        self.pushButtonSetting.setText(_translate("CityDiffusionWindow", "Setting", None))
        self.label_7.setText(_translate("CityDiffusionWindow", "Fixed temporal weights", None))
        self.pushButtonDifferentValue.setText(_translate("CityDiffusionWindow", "Variable temporal weights", None))
        self.groupBox_2.setTitle(_translate("CityDiffusionWindow", "Network", None))
        self.groupBox_3.setTitle(_translate("CityDiffusionWindow", "Termination", None))
        self.pushButtonClear.setText(_translate("CityDiffusionWindow", "Clear", None))
        self.radioButtonPercentage.setText(_translate("CityDiffusionWindow", "Percentage of coverage(%)", None))
        self.radioButtonSteps.setText(_translate("CityDiffusionWindow", "The number of steps", None))
        self.groupBox_4.setTitle(_translate("CityDiffusionWindow", "Spatial Weight", None))
        self.radioButtonRegional.setText(_translate("CityDiffusionWindow", "Decaying", None))
        self.label_5.setText(_translate("CityDiffusionWindow", "Decayed radius(mile)", None))
        self.radioButtonGlobal.setText(_translate("CityDiffusionWindow", "Fixed", None))
        self.label_6.setText(_translate("CityDiffusionWindow", "Decayed ratio(%)", None))
        self.groupBox_5.setTitle(_translate("CityDiffusionWindow", "Event Urgency", None))
        self.groupBoxPreview.setTitle(_translate("CityDiffusionWindow", "Preview", None))

