# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\SocialNetworkSimulator\UI\MainForm.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1866, 902)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBoxNetworkAnalysis = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxNetworkAnalysis.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(9)
        self.groupBoxNetworkAnalysis.setFont(font)
        self.groupBoxNetworkAnalysis.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxNetworkAnalysis.setObjectName(_fromUtf8("groupBoxNetworkAnalysis"))
        self.groupBoxNetworkCharactor = QtGui.QGroupBox(self.groupBoxNetworkAnalysis)
        self.groupBoxNetworkCharactor.setGeometry(QtCore.QRect(5, 30, 240, 261))
        self.groupBoxNetworkCharactor.setObjectName(_fromUtf8("groupBoxNetworkCharactor"))
        self.pushButton = QtGui.QPushButton(self.groupBoxNetworkCharactor)
        self.pushButton.setGeometry(QtCore.QRect(20, 180, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.groupBoxNetworkCharactor)
        self.pushButton_2.setGeometry(QtCore.QRect(130, 180, 75, 23))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButtonNetworkcharacteristic = QtGui.QPushButton(self.groupBoxNetworkCharactor)
        self.pushButtonNetworkcharacteristic.setGeometry(QtCore.QRect(150, 220, 75, 23))
        self.pushButtonNetworkcharacteristic.setObjectName(_fromUtf8("pushButtonNetworkcharacteristic"))
        self.tableWidgetNetworkCharacteristics = QtGui.QTableWidget(self.groupBoxNetworkCharactor)
        self.tableWidgetNetworkCharacteristics.setGeometry(QtCore.QRect(10, 20, 221, 192))
        self.tableWidgetNetworkCharacteristics.setObjectName(_fromUtf8("tableWidgetNetworkCharacteristics"))
        self.tableWidgetNetworkCharacteristics.setColumnCount(2)
        self.tableWidgetNetworkCharacteristics.setRowCount(4)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.tableWidgetNetworkCharacteristics.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetNetworkCharacteristics.setItem(3, 1, item)
        self.groupBox = QtGui.QGroupBox(self.groupBoxNetworkAnalysis)
        self.groupBox.setGeometry(QtCore.QRect(5, 300, 240, 161))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pushButtonDegreeCentrality = QtGui.QPushButton(self.groupBox)
        self.pushButtonDegreeCentrality.setGeometry(QtCore.QRect(50, 30, 141, 23))
        self.pushButtonDegreeCentrality.setObjectName(_fromUtf8("pushButtonDegreeCentrality"))
        self.pushButtonBetweennessCentrality = QtGui.QPushButton(self.groupBox)
        self.pushButtonBetweennessCentrality.setGeometry(QtCore.QRect(50, 60, 141, 23))
        self.pushButtonBetweennessCentrality.setObjectName(_fromUtf8("pushButtonBetweennessCentrality"))
        self.pushButtonClosenessCentrality = QtGui.QPushButton(self.groupBox)
        self.pushButtonClosenessCentrality.setGeometry(QtCore.QRect(50, 90, 141, 23))
        self.pushButtonClosenessCentrality.setObjectName(_fromUtf8("pushButtonClosenessCentrality"))
        self.pushButtonEigenvCentrality = QtGui.QPushButton(self.groupBox)
        self.pushButtonEigenvCentrality.setGeometry(QtCore.QRect(50, 120, 141, 23))
        self.pushButtonEigenvCentrality.setObjectName(_fromUtf8("pushButtonEigenvCentrality"))
        self.horizontalLayout.addWidget(self.groupBoxNetworkAnalysis)
        self.groupBoxNetworkGenerator = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxNetworkGenerator.sizePolicy().hasHeightForWidth())
        self.groupBoxNetworkGenerator.setSizePolicy(sizePolicy)
        self.groupBoxNetworkGenerator.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(9)
        self.groupBoxNetworkGenerator.setFont(font)
        self.groupBoxNetworkGenerator.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxNetworkGenerator.setFlat(False)
        self.groupBoxNetworkGenerator.setObjectName(_fromUtf8("groupBoxNetworkGenerator"))
        self.comboBoxNetworkType = QtGui.QComboBox(self.groupBoxNetworkGenerator)
        self.comboBoxNetworkType.setGeometry(QtCore.QRect(100, 30, 141, 20))
        self.comboBoxNetworkType.setObjectName(_fromUtf8("comboBoxNetworkType"))
        self.label = QtGui.QLabel(self.groupBoxNetworkGenerator)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.labelConfigureParameters = QtGui.QLabel(self.groupBoxNetworkGenerator)
        self.labelConfigureParameters.setGeometry(QtCore.QRect(10, 60, 191, 16))
        self.labelConfigureParameters.setObjectName(_fromUtf8("labelConfigureParameters"))
        self.tableWidgetParameter = QtGui.QTableWidget(self.groupBoxNetworkGenerator)
        self.tableWidgetParameter.setGeometry(QtCore.QRect(10, 80, 231, 291))
        self.tableWidgetParameter.setObjectName(_fromUtf8("tableWidgetParameter"))
        self.tableWidgetParameter.setColumnCount(2)
        self.tableWidgetParameter.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Parameter"))
        self.tableWidgetParameter.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParameter.setHorizontalHeaderItem(1, item)
        self.pushButtonGenerateNetwork = QtGui.QPushButton(self.groupBoxNetworkGenerator)
        self.pushButtonGenerateNetwork.setGeometry(QtCore.QRect(121, 532, 115, 23))
        self.pushButtonGenerateNetwork.setObjectName(_fromUtf8("pushButtonGenerateNetwork"))
        self.checkBoxEdge = QtGui.QCheckBox(self.groupBoxNetworkGenerator)
        self.checkBoxEdge.setGeometry(QtCore.QRect(21, 533, 88, 19))
        self.checkBoxEdge.setChecked(True)
        self.checkBoxEdge.setObjectName(_fromUtf8("checkBoxEdge"))
        self.pushButtonRestNetwork = QtGui.QPushButton(self.groupBoxNetworkGenerator)
        self.pushButtonRestNetwork.setGeometry(QtCore.QRect(121, 570, 115, 23))
        self.pushButtonRestNetwork.setObjectName(_fromUtf8("pushButtonRestNetwork"))
        self.groupBoxBaseMap = QtGui.QGroupBox(self.groupBoxNetworkGenerator)
        self.groupBoxBaseMap.setGeometry(QtCore.QRect(10, 390, 231, 121))
        self.groupBoxBaseMap.setCheckable(True)
        self.groupBoxBaseMap.setChecked(False)
        self.groupBoxBaseMap.setObjectName(_fromUtf8("groupBoxBaseMap"))
        self.lineEditPathName = QtGui.QLineEdit(self.groupBoxBaseMap)
        self.lineEditPathName.setGeometry(QtCore.QRect(11, 52, 151, 21))
        self.lineEditPathName.setObjectName(_fromUtf8("lineEditPathName"))
        self.pushButtonSelectBaseMap = QtGui.QPushButton(self.groupBoxBaseMap)
        self.pushButtonSelectBaseMap.setGeometry(QtCore.QRect(164, 51, 61, 23))
        self.pushButtonSelectBaseMap.setObjectName(_fromUtf8("pushButtonSelectBaseMap"))
        self.comboBoxBaseMapLayers = QtGui.QComboBox(self.groupBoxBaseMap)
        self.comboBoxBaseMapLayers.setGeometry(QtCore.QRect(11, 82, 151, 21))
        self.comboBoxBaseMapLayers.setObjectName(_fromUtf8("comboBoxBaseMapLayers"))
        self.pushButtonViewBaseMap = QtGui.QPushButton(self.groupBoxBaseMap)
        self.pushButtonViewBaseMap.setGeometry(QtCore.QRect(164, 80, 61, 23))
        self.pushButtonViewBaseMap.setObjectName(_fromUtf8("pushButtonViewBaseMap"))
        self.labelSelectBaseMap = QtGui.QLabel(self.groupBoxBaseMap)
        self.labelSelectBaseMap.setGeometry(QtCore.QRect(10, 30, 181, 16))
        self.labelSelectBaseMap.setObjectName(_fromUtf8("labelSelectBaseMap"))
        self.horizontalLayout.addWidget(self.groupBoxNetworkGenerator)
        self.groupBoxFindParameters = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxFindParameters.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(9)
        self.groupBoxFindParameters.setFont(font)
        self.groupBoxFindParameters.setObjectName(_fromUtf8("groupBoxFindParameters"))
        self.textEditSeedNodes = QtGui.QTextEdit(self.groupBoxFindParameters)
        self.textEditSeedNodes.setGeometry(QtCore.QRect(10, 50, 221, 171))
        self.textEditSeedNodes.setFrameShape(QtGui.QFrame.StyledPanel)
        self.textEditSeedNodes.setObjectName(_fromUtf8("textEditSeedNodes"))
        self.label_2 = QtGui.QLabel(self.groupBoxFindParameters)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 88, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalSliderPleader = QtGui.QSlider(self.groupBoxFindParameters)
        self.horizontalSliderPleader.setEnabled(False)
        self.horizontalSliderPleader.setGeometry(QtCore.QRect(109, 250, 121, 20))
        self.horizontalSliderPleader.setMaximum(1000)
        self.horizontalSliderPleader.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPleader.setObjectName(_fromUtf8("horizontalSliderPleader"))
        self.label_3 = QtGui.QLabel(self.groupBoxFindParameters)
        self.label_3.setGeometry(QtCore.QRect(10, 250, 71, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.groupBoxFindParameters)
        self.label_4.setGeometry(QtCore.QRect(10, 300, 71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_pleader_value = QtGui.QLabel(self.groupBoxFindParameters)
        self.label_pleader_value.setGeometry(QtCore.QRect(110, 270, 111, 16))
        self.label_pleader_value.setObjectName(_fromUtf8("label_pleader_value"))
        self.horizontalSliderPNormal = QtGui.QSlider(self.groupBoxFindParameters)
        self.horizontalSliderPNormal.setEnabled(False)
        self.horizontalSliderPNormal.setGeometry(QtCore.QRect(109, 300, 121, 20))
        self.horizontalSliderPNormal.setMaximum(1000)
        self.horizontalSliderPNormal.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderPNormal.setObjectName(_fromUtf8("horizontalSliderPNormal"))
        self.label_padopter_value = QtGui.QLabel(self.groupBoxFindParameters)
        self.label_padopter_value.setGeometry(QtCore.QRect(110, 320, 111, 16))
        self.label_padopter_value.setObjectName(_fromUtf8("label_padopter_value"))
        self.pushButtonFindParameters = QtGui.QPushButton(self.groupBoxFindParameters)
        self.pushButtonFindParameters.setGeometry(QtCore.QRect(110, 360, 121, 23))
        self.pushButtonFindParameters.setObjectName(_fromUtf8("pushButtonFindParameters"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBoxFindParameters)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 410, 231, 151))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(6, 90, 61, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(6, 30, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.lineEditParameterFile = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditParameterFile.setGeometry(QtCore.QRect(7, 52, 133, 23))
        self.lineEditParameterFile.setObjectName(_fromUtf8("lineEditParameterFile"))
        self.pushButtonOpenParameter = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonOpenParameter.setGeometry(QtCore.QRect(146, 51, 75, 25))
        self.pushButtonOpenParameter.setObjectName(_fromUtf8("pushButtonOpenParameter"))
        self.lineEditMapTitle = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditMapTitle.setGeometry(QtCore.QRect(7, 112, 133, 23))
        self.lineEditMapTitle.setObjectName(_fromUtf8("lineEditMapTitle"))
        self.pushButtonDrawCounterMap = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonDrawCounterMap.setGeometry(QtCore.QRect(146, 111, 75, 25))
        self.pushButtonDrawCounterMap.setObjectName(_fromUtf8("pushButtonDrawCounterMap"))
        self.horizontalLayout.addWidget(self.groupBoxFindParameters)
        self.groupBoxSimulator = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxSimulator.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(9)
        self.groupBoxSimulator.setFont(font)
        self.groupBoxSimulator.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxSimulator.setObjectName(_fromUtf8("groupBoxSimulator"))
        self.groupBoxLTModel = QtGui.QGroupBox(self.groupBoxSimulator)
        self.groupBoxLTModel.setGeometry(QtCore.QRect(10, 350, 231, 71))
        self.groupBoxLTModel.setCheckable(True)
        self.groupBoxLTModel.setChecked(False)
        self.groupBoxLTModel.setObjectName(_fromUtf8("groupBoxLTModel"))
        self.labelThreshold = QtGui.QLabel(self.groupBoxLTModel)
        self.labelThreshold.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.labelThreshold.setObjectName(_fromUtf8("labelThreshold"))
        self.lineEditThreshold = QtGui.QLineEdit(self.groupBoxLTModel)
        self.lineEditThreshold.setGeometry(QtCore.QRect(80, 40, 141, 20))
        self.lineEditThreshold.setInputMask(_fromUtf8(""))
        self.lineEditThreshold.setText(_fromUtf8(""))
        self.lineEditThreshold.setMaxLength(32767)
        self.lineEditThreshold.setObjectName(_fromUtf8("lineEditThreshold"))
        self.groupBoxSeedNodes = QtGui.QGroupBox(self.groupBoxSimulator)
        self.groupBoxSeedNodes.setGeometry(QtCore.QRect(10, 30, 231, 141))
        self.groupBoxSeedNodes.setObjectName(_fromUtf8("groupBoxSeedNodes"))
        self.comboBoxAlgorithmsforSeedNode = QtGui.QComboBox(self.groupBoxSeedNodes)
        self.comboBoxAlgorithmsforSeedNode.setGeometry(QtCore.QRect(80, 60, 141, 21))
        self.comboBoxAlgorithmsforSeedNode.setObjectName(_fromUtf8("comboBoxAlgorithmsforSeedNode"))
        self.labelNumberofSeeds = QtGui.QLabel(self.groupBoxSeedNodes)
        self.labelNumberofSeeds.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.labelNumberofSeeds.setObjectName(_fromUtf8("labelNumberofSeeds"))
        self.labelSelectSeedsAlgorithm = QtGui.QLabel(self.groupBoxSeedNodes)
        self.labelSelectSeedsAlgorithm.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.labelSelectSeedsAlgorithm.setObjectName(_fromUtf8("labelSelectSeedsAlgorithm"))
        self.lineEditNumberofSeedNodes = QtGui.QLineEdit(self.groupBoxSeedNodes)
        self.lineEditNumberofSeedNodes.setGeometry(QtCore.QRect(80, 30, 141, 20))
        self.lineEditNumberofSeedNodes.setObjectName(_fromUtf8("lineEditNumberofSeedNodes"))
        self.pushButtonGenerateSeedNodes = QtGui.QPushButton(self.groupBoxSeedNodes)
        self.pushButtonGenerateSeedNodes.setGeometry(QtCore.QRect(80, 100, 141, 23))
        self.pushButtonGenerateSeedNodes.setObjectName(_fromUtf8("pushButtonGenerateSeedNodes"))
        self.groupBoxICModel = QtGui.QGroupBox(self.groupBoxSimulator)
        self.groupBoxICModel.setGeometry(QtCore.QRect(10, 430, 231, 131))
        self.groupBoxICModel.setCheckable(True)
        self.groupBoxICModel.setChecked(False)
        self.groupBoxICModel.setObjectName(_fromUtf8("groupBoxICModel"))
        self.labelOpinionNodePogagate = QtGui.QLabel(self.groupBoxICModel)
        self.labelOpinionNodePogagate.setGeometry(QtCore.QRect(10, 30, 221, 16))
        self.labelOpinionNodePogagate.setObjectName(_fromUtf8("labelOpinionNodePogagate"))
        self.lineEditOpinionNodePopagate = QtGui.QLineEdit(self.groupBoxICModel)
        self.lineEditOpinionNodePopagate.setGeometry(QtCore.QRect(80, 50, 141, 20))
        self.lineEditOpinionNodePopagate.setObjectName(_fromUtf8("lineEditOpinionNodePopagate"))
        self.labelNormalNodePopagate = QtGui.QLabel(self.groupBoxICModel)
        self.labelNormalNodePopagate.setGeometry(QtCore.QRect(10, 80, 211, 16))
        self.labelNormalNodePopagate.setObjectName(_fromUtf8("labelNormalNodePopagate"))
        self.lineEditNormalNodePopagate = QtGui.QLineEdit(self.groupBoxICModel)
        self.lineEditNormalNodePopagate.setGeometry(QtCore.QRect(80, 100, 141, 20))
        self.lineEditNormalNodePopagate.setObjectName(_fromUtf8("lineEditNormalNodePopagate"))
        self.pushButtonDiffusion = QtGui.QPushButton(self.groupBoxSimulator)
        self.pushButtonDiffusion.setGeometry(QtCore.QRect(100, 570, 141, 23))
        self.pushButtonDiffusion.setObjectName(_fromUtf8("pushButtonDiffusion"))
        self.groupBoxOpinionLeaders = QtGui.QGroupBox(self.groupBoxSimulator)
        self.groupBoxOpinionLeaders.setGeometry(QtCore.QRect(10, 180, 231, 161))
        self.groupBoxOpinionLeaders.setCheckable(False)
        self.groupBoxOpinionLeaders.setChecked(False)
        self.groupBoxOpinionLeaders.setObjectName(_fromUtf8("groupBoxOpinionLeaders"))
        self.radioButtonWholeNetwork = QtGui.QRadioButton(self.groupBoxOpinionLeaders)
        self.radioButtonWholeNetwork.setGeometry(QtCore.QRect(10, 30, 121, 17))
        self.radioButtonWholeNetwork.setChecked(True)
        self.radioButtonWholeNetwork.setObjectName(_fromUtf8("radioButtonWholeNetwork"))
        self.radioButtonEachCommunity = QtGui.QRadioButton(self.groupBoxOpinionLeaders)
        self.radioButtonEachCommunity.setGeometry(QtCore.QRect(10, 50, 131, 17))
        self.radioButtonEachCommunity.setObjectName(_fromUtf8("radioButtonEachCommunity"))
        self.splitter = QtGui.QSplitter(self.groupBoxOpinionLeaders)
        self.splitter.setGeometry(QtCore.QRect(10, 80, 220, 23))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.label_8 = QtGui.QLabel(self.splitter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEditPropotion = QtGui.QLineEdit(self.splitter)
        self.lineEditPropotion.setObjectName(_fromUtf8("lineEditPropotion"))
        self.label_7 = QtGui.QLabel(self.splitter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButtonGenerateOpinionLeaders = QtGui.QPushButton(self.groupBoxOpinionLeaders)
        self.pushButtonGenerateOpinionLeaders.setGeometry(QtCore.QRect(60, 120, 161, 23))
        self.pushButtonGenerateOpinionLeaders.setObjectName(_fromUtf8("pushButtonGenerateOpinionLeaders"))
        self.horizontalLayout.addWidget(self.groupBoxSimulator)
        self.groupBoxComplexNetwork = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxComplexNetwork.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxComplexNetwork.sizePolicy().hasHeightForWidth())
        self.groupBoxComplexNetwork.setSizePolicy(sizePolicy)
        self.groupBoxComplexNetwork.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBoxComplexNetwork.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(9)
        self.groupBoxComplexNetwork.setFont(font)
        self.groupBoxComplexNetwork.setMouseTracking(True)
        self.groupBoxComplexNetwork.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxComplexNetwork.setObjectName(_fromUtf8("groupBoxComplexNetwork"))
        self.tableWidgetComplexLinks = QtGui.QTableWidget(self.groupBoxComplexNetwork)
        self.tableWidgetComplexLinks.setGeometry(QtCore.QRect(8, 550, 235, 91))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetComplexLinks.sizePolicy().hasHeightForWidth())
        self.tableWidgetComplexLinks.setSizePolicy(sizePolicy)
        self.tableWidgetComplexLinks.setCornerButtonEnabled(True)
        self.tableWidgetComplexLinks.setObjectName(_fromUtf8("tableWidgetComplexLinks"))
        self.tableWidgetComplexLinks.setColumnCount(6)
        self.tableWidgetComplexLinks.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetComplexLinks.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetComplexLinks.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetComplexLinks.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetComplexLinks.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetComplexLinks.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetComplexLinks.setHorizontalHeaderItem(5, item)
        self.lineEditNetworkCount = QtGui.QLineEdit(self.groupBoxComplexNetwork)
        self.lineEditNetworkCount.setGeometry(QtCore.QRect(11, 62, 133, 21))
        self.lineEditNetworkCount.setObjectName(_fromUtf8("lineEditNetworkCount"))
        self.pushButtonOKforNetworkCount = QtGui.QPushButton(self.groupBoxComplexNetwork)
        self.pushButtonOKforNetworkCount.setGeometry(QtCore.QRect(150, 61, 75, 23))
        self.pushButtonOKforNetworkCount.setObjectName(_fromUtf8("pushButtonOKforNetworkCount"))
        self.labelNetworkCount = QtGui.QLabel(self.groupBoxComplexNetwork)
        self.labelNetworkCount.setGeometry(QtCore.QRect(10, 40, 191, 20))
        self.labelNetworkCount.setObjectName(_fromUtf8("labelNetworkCount"))
        self.groupBoxEverySimpleNetwork = QtGui.QGroupBox(self.groupBoxComplexNetwork)
        self.groupBoxEverySimpleNetwork.setGeometry(QtCore.QRect(2, 220, 241, 271))
        self.groupBoxEverySimpleNetwork.setObjectName(_fromUtf8("groupBoxEverySimpleNetwork"))
        self.comboBoxNetworkID = QtGui.QComboBox(self.groupBoxEverySimpleNetwork)
        self.comboBoxNetworkID.setGeometry(QtCore.QRect(90, 30, 141, 21))
        self.comboBoxNetworkID.setObjectName(_fromUtf8("comboBoxNetworkID"))
        self.labelNetworkID = QtGui.QLabel(self.groupBoxEverySimpleNetwork)
        self.labelNetworkID.setGeometry(QtCore.QRect(20, 30, 71, 16))
        self.labelNetworkID.setObjectName(_fromUtf8("labelNetworkID"))
        self.labelNetworkTypeSingle = QtGui.QLabel(self.groupBoxEverySimpleNetwork)
        self.labelNetworkTypeSingle.setGeometry(QtCore.QRect(8, 60, 81, 20))
        self.labelNetworkTypeSingle.setObjectName(_fromUtf8("labelNetworkTypeSingle"))
        self.comboBoxNetworkTypeforComplex = QtGui.QComboBox(self.groupBoxEverySimpleNetwork)
        self.comboBoxNetworkTypeforComplex.setGeometry(QtCore.QRect(90, 60, 141, 21))
        self.comboBoxNetworkTypeforComplex.setObjectName(_fromUtf8("comboBoxNetworkTypeforComplex"))
        self.tableWidgetParameterComplexParameters = QtGui.QTableWidget(self.groupBoxEverySimpleNetwork)
        self.tableWidgetParameterComplexParameters.setGeometry(QtCore.QRect(5, 90, 231, 111))
        self.tableWidgetParameterComplexParameters.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidgetParameterComplexParameters.setObjectName(_fromUtf8("tableWidgetParameterComplexParameters"))
        self.tableWidgetParameterComplexParameters.setColumnCount(2)
        self.tableWidgetParameterComplexParameters.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setText(_fromUtf8("Parameter"))
        self.tableWidgetParameterComplexParameters.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidgetParameterComplexParameters.setHorizontalHeaderItem(1, item)
        self.pushButtonOverview = QtGui.QPushButton(self.groupBoxEverySimpleNetwork)
        self.pushButtonOverview.setGeometry(QtCore.QRect(60, 240, 171, 23))
        self.pushButtonOverview.setObjectName(_fromUtf8("pushButtonOverview"))
        self.pushButtonSaveComplexNetworkParams = QtGui.QPushButton(self.groupBoxEverySimpleNetwork)
        self.pushButtonSaveComplexNetworkParams.setGeometry(QtCore.QRect(60, 210, 171, 23))
        self.pushButtonSaveComplexNetworkParams.setObjectName(_fromUtf8("pushButtonSaveComplexNetworkParams"))
        self.labelNetworkCount_2 = QtGui.QLabel(self.groupBoxComplexNetwork)
        self.labelNetworkCount_2.setGeometry(QtCore.QRect(11, 491, 107, 16))
        self.labelNetworkCount_2.setObjectName(_fromUtf8("labelNetworkCount_2"))
        self.pushButtonExpandShrink = QtGui.QPushButton(self.groupBoxComplexNetwork)
        self.pushButtonExpandShrink.setGeometry(QtCore.QRect(124, 490, 111, 23))
        self.pushButtonExpandShrink.setObjectName(_fromUtf8("pushButtonExpandShrink"))
        self.groupBoxBaseMapComplex = QtGui.QGroupBox(self.groupBoxComplexNetwork)
        self.groupBoxBaseMapComplex.setGeometry(QtCore.QRect(10, 90, 231, 121))
        self.groupBoxBaseMapComplex.setCheckable(True)
        self.groupBoxBaseMapComplex.setChecked(False)
        self.groupBoxBaseMapComplex.setObjectName(_fromUtf8("groupBoxBaseMapComplex"))
        self.lineEditPathNameComplex = QtGui.QLineEdit(self.groupBoxBaseMapComplex)
        self.lineEditPathNameComplex.setGeometry(QtCore.QRect(11, 52, 151, 21))
        self.lineEditPathNameComplex.setObjectName(_fromUtf8("lineEditPathNameComplex"))
        self.pushButtonSelectBaseMapComplex = QtGui.QPushButton(self.groupBoxBaseMapComplex)
        self.pushButtonSelectBaseMapComplex.setGeometry(QtCore.QRect(164, 51, 61, 23))
        self.pushButtonSelectBaseMapComplex.setObjectName(_fromUtf8("pushButtonSelectBaseMapComplex"))
        self.comboBoxBaseMapLayersComplex = QtGui.QComboBox(self.groupBoxBaseMapComplex)
        self.comboBoxBaseMapLayersComplex.setGeometry(QtCore.QRect(11, 82, 151, 21))
        self.comboBoxBaseMapLayersComplex.setFrame(False)
        self.comboBoxBaseMapLayersComplex.setObjectName(_fromUtf8("comboBoxBaseMapLayersComplex"))
        self.pushButtonViewBaseMapComplex = QtGui.QPushButton(self.groupBoxBaseMapComplex)
        self.pushButtonViewBaseMapComplex.setGeometry(QtCore.QRect(164, 80, 61, 23))
        self.pushButtonViewBaseMapComplex.setObjectName(_fromUtf8("pushButtonViewBaseMapComplex"))
        self.labelSelectBaseMapComplex = QtGui.QLabel(self.groupBoxBaseMapComplex)
        self.labelSelectBaseMapComplex.setGeometry(QtCore.QRect(10, 30, 181, 16))
        self.labelSelectBaseMapComplex.setObjectName(_fromUtf8("labelSelectBaseMapComplex"))
        self.pushButtonRemoveConnect = QtGui.QPushButton(self.groupBoxComplexNetwork)
        self.pushButtonRemoveConnect.setGeometry(QtCore.QRect(124, 520, 111, 23))
        self.pushButtonRemoveConnect.setObjectName(_fromUtf8("pushButtonRemoveConnect"))
        self.pushButtonAddConnect = QtGui.QPushButton(self.groupBoxComplexNetwork)
        self.pushButtonAddConnect.setGeometry(QtCore.QRect(10, 520, 101, 23))
        self.pushButtonAddConnect.setObjectName(_fromUtf8("pushButtonAddConnect"))
        self.pushButtonGenerateComplexNetwork = QtGui.QPushButton(self.groupBoxComplexNetwork)
        self.pushButtonGenerateComplexNetwork.setGeometry(QtCore.QRect(64, 650, 181, 23))
        self.pushButtonGenerateComplexNetwork.setObjectName(_fromUtf8("pushButtonGenerateComplexNetwork"))
        self.horizontalLayout.addWidget(self.groupBoxComplexNetwork)
        self.groupBoxCommunity = QtGui.QGroupBox(self.centralwidget)
        self.groupBoxCommunity.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(9)
        self.groupBoxCommunity.setFont(font)
        self.groupBoxCommunity.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxCommunity.setObjectName(_fromUtf8("groupBoxCommunity"))
        self.tableWidgetCommunity = QtGui.QTableWidget(self.groupBoxCommunity)
        self.tableWidgetCommunity.setGeometry(QtCore.QRect(10, 80, 231, 192))
        self.tableWidgetCommunity.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidgetCommunity.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidgetCommunity.setObjectName(_fromUtf8("tableWidgetCommunity"))
        self.tableWidgetCommunity.setColumnCount(2)
        self.tableWidgetCommunity.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidgetCommunity.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.tableWidgetCommunity.setHorizontalHeaderItem(1, item)
        self.label_9 = QtGui.QLabel(self.groupBoxCommunity)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 71, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout.addWidget(self.groupBoxCommunity)
        self.groupBoxPreview = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPreview.sizePolicy().hasHeightForWidth())
        self.groupBoxPreview.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(9)
        self.groupBoxPreview.setFont(font)
        self.groupBoxPreview.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBoxPreview.setFlat(False)
        self.groupBoxPreview.setCheckable(False)
        self.groupBoxPreview.setObjectName(_fromUtf8("groupBoxPreview"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBoxPreview)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.FrameCanvas = QtGui.QWidget(self.groupBoxPreview)
        self.FrameCanvas.setEnabled(True)
        self.FrameCanvas.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.FrameCanvas.setObjectName(_fromUtf8("FrameCanvas"))
        self.gridLayout = QtGui.QGridLayout(self.FrameCanvas)
        self.gridLayout.setMargin(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_2.addWidget(self.FrameCanvas)
        self.horizontalLayout.addWidget(self.groupBoxPreview)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1866, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuNetwork = QtGui.QMenu(self.menubar)
        self.menuNetwork.setObjectName(_fromUtf8("menuNetwork"))
        self.menuAnalysis = QtGui.QMenu(self.menubar)
        self.menuAnalysis.setObjectName(_fromUtf8("menuAnalysis"))
        self.menuSimulator = QtGui.QMenu(self.menubar)
        self.menuSimulator.setObjectName(_fromUtf8("menuSimulator"))
        self.menuCommunity = QtGui.QMenu(self.menubar)
        self.menuCommunity.setObjectName(_fromUtf8("menuCommunity"))
        self.menuData = QtGui.QMenu(self.menubar)
        self.menuData.setObjectName(_fromUtf8("menuData"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.actionSave_As = QtGui.QAction(MainWindow)
        self.actionSave_As.setObjectName(_fromUtf8("actionSave_As"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionFindParameters = QtGui.QAction(MainWindow)
        self.actionFindParameters.setObjectName(_fromUtf8("actionFindParameters"))
        self.actionDemonstrate_Temporal_Spatial_Process = QtGui.QAction(MainWindow)
        self.actionDemonstrate_Temporal_Spatial_Process.setObjectName(_fromUtf8("actionDemonstrate_Temporal_Spatial_Process"))
        self.actionGeoDataFromTweets = QtGui.QAction(MainWindow)
        self.actionGeoDataFromTweets.setObjectName(_fromUtf8("actionGeoDataFromTweets"))
        self.actionSocialNetworkFromTweets = QtGui.QAction(MainWindow)
        self.actionSocialNetworkFromTweets.setObjectName(_fromUtf8("actionSocialNetworkFromTweets"))
        self.actionGenerate_Simulated_Network = QtGui.QAction(MainWindow)
        self.actionGenerate_Simulated_Network.setObjectName(_fromUtf8("actionGenerate_Simulated_Network"))
        self.actionNetwork_Analysis = QtGui.QAction(MainWindow)
        self.actionNetwork_Analysis.setObjectName(_fromUtf8("actionNetwork_Analysis"))
        self.actionWindowNetwork_Analysis = QtGui.QAction(MainWindow)
        self.actionWindowNetwork_Analysis.setObjectName(_fromUtf8("actionWindowNetwork_Analysis"))
        self.actionWindowNetwork_Generator = QtGui.QAction(MainWindow)
        self.actionWindowNetwork_Generator.setObjectName(_fromUtf8("actionWindowNetwork_Generator"))
        self.actionWindowSimulating_Information_Diffusion = QtGui.QAction(MainWindow)
        self.actionWindowSimulating_Information_Diffusion.setObjectName(_fromUtf8("actionWindowSimulating_Information_Diffusion"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDocument = QtGui.QAction(MainWindow)
        self.actionDocument.setObjectName(_fromUtf8("actionDocument"))
        self.actionGenerate_Complex_Network = QtGui.QAction(MainWindow)
        self.actionGenerate_Complex_Network.setObjectName(_fromUtf8("actionGenerate_Complex_Network"))
        self.actionCNM = QtGui.QAction(MainWindow)
        self.actionCNM.setObjectName(_fromUtf8("actionCNM"))
        self.actionGirvanNewman = QtGui.QAction(MainWindow)
        self.actionGirvanNewman.setObjectName(_fromUtf8("actionGirvanNewman"))
        self.actionOSLOM = QtGui.QAction(MainWindow)
        self.actionOSLOM.setObjectName(_fromUtf8("actionOSLOM"))
        self.actionCollect_tweets_by_Account = QtGui.QAction(MainWindow)
        self.actionCollect_tweets_by_Account.setObjectName(_fromUtf8("actionCollect_tweets_by_Account"))
        self.actionExtract_Social_Network = QtGui.QAction(MainWindow)
        self.actionExtract_Social_Network.setObjectName(_fromUtf8("actionExtract_Social_Network"))
        self.actionMerge_Network = QtGui.QAction(MainWindow)
        self.actionMerge_Network.setObjectName(_fromUtf8("actionMerge_Network"))
        self.actionPredict_Diffusion = QtGui.QAction(MainWindow)
        self.actionPredict_Diffusion.setObjectName(_fromUtf8("actionPredict_Diffusion"))
        self.actionLoad_Network = QtGui.QAction(MainWindow)
        self.actionLoad_Network.setObjectName(_fromUtf8("actionLoad_Network"))
        self.actionInformation_Diffusion_City = QtGui.QAction(MainWindow)
        self.actionInformation_Diffusion_City.setObjectName(_fromUtf8("actionInformation_Diffusion_City"))
        self.actionUser = QtGui.QAction(MainWindow)
        self.actionUser.setObjectName(_fromUtf8("actionUser"))
        self.actionCity = QtGui.QAction(MainWindow)
        self.actionCity.setObjectName(_fromUtf8("actionCity"))
        self.menuInformation_Diffusion_City = QtGui.QAction(MainWindow)
        self.menuInformation_Diffusion_City.setObjectName(_fromUtf8("menuInformation_Diffusion_City"))
        self.actionExtract_Diffusion_Network = QtGui.QAction(MainWindow)
        self.actionExtract_Diffusion_Network.setObjectName(_fromUtf8("actionExtract_Diffusion_Network"))
        self.actionExtract_Mentioned_Network = QtGui.QAction(MainWindow)
        self.actionExtract_Mentioned_Network.setObjectName(_fromUtf8("actionExtract_Mentioned_Network"))
        self.actionCompute_Weight_Matrix = QtGui.QAction(MainWindow)
        self.actionCompute_Weight_Matrix.setObjectName(_fromUtf8("actionCompute_Weight_Matrix"))
        self.actionSave_Network = QtGui.QAction(MainWindow)
        self.actionSave_Network.setObjectName(_fromUtf8("actionSave_Network"))
        self.menuInformation_Diffusion_User_2 = QtGui.QAction(MainWindow)
        self.menuInformation_Diffusion_User_2.setObjectName(_fromUtf8("menuInformation_Diffusion_User_2"))
        self.actionUser_Level = QtGui.QAction(MainWindow)
        self.actionUser_Level.setObjectName(_fromUtf8("actionUser_Level"))
        self.actionCity_Level = QtGui.QAction(MainWindow)
        self.actionCity_Level.setObjectName(_fromUtf8("actionCity_Level"))
        self.actionUser_Manual = QtGui.QAction(MainWindow)
        self.actionUser_Manual.setObjectName(_fromUtf8("actionUser_Manual"))
        self.actionAbout_2 = QtGui.QAction(MainWindow)
        self.actionAbout_2.setObjectName(_fromUtf8("actionAbout_2"))
        self.menuNetwork.addAction(self.actionGenerate_Simulated_Network)
        self.menuNetwork.addAction(self.actionGenerate_Complex_Network)
        self.menuNetwork.addAction(self.actionSave_Network)
        self.menuNetwork.addAction(self.actionLoad_Network)
        self.menuAnalysis.addAction(self.actionNetwork_Analysis)
        self.menuSimulator.addAction(self.actionUser_Level)
        self.menuSimulator.addAction(self.actionCity_Level)
        self.menuCommunity.addAction(self.actionCNM)
        self.menuData.addAction(self.actionExtract_Diffusion_Network)
        self.menuData.addAction(self.actionExtract_Mentioned_Network)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuNetwork.menuAction())
        self.menubar.addAction(self.menuAnalysis.menuAction())
        self.menubar.addAction(self.menuCommunity.menuAction())
        self.menubar.addAction(self.menuSimulator.menuAction())
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "NetworkSimulator", None))
        self.groupBoxNetworkAnalysis.setTitle(_translate("MainWindow", "Network Analysis", None))
        self.groupBoxNetworkCharactor.setTitle(_translate("MainWindow", "Network Characteristics", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton", None))
        self.pushButtonNetworkcharacteristic.setText(_translate("MainWindow", "Run", None))
        item = self.tableWidgetNetworkCharacteristics.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.tableWidgetNetworkCharacteristics.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.tableWidgetNetworkCharacteristics.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.tableWidgetNetworkCharacteristics.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.tableWidgetNetworkCharacteristics.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Character", None))
        item = self.tableWidgetNetworkCharacteristics.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        __sortingEnabled = self.tableWidgetNetworkCharacteristics.isSortingEnabled()
        self.tableWidgetNetworkCharacteristics.setSortingEnabled(False)
        item = self.tableWidgetNetworkCharacteristics.item(0, 0)
        item.setText(_translate("MainWindow", "# Nodes", None))
        item = self.tableWidgetNetworkCharacteristics.item(1, 0)
        item.setText(_translate("MainWindow", "# Edges", None))
        item = self.tableWidgetNetworkCharacteristics.item(2, 0)
        item.setText(_translate("MainWindow", "Modularity", None))
        item = self.tableWidgetNetworkCharacteristics.item(3, 0)
        item.setText(_translate("MainWindow", "Diameter", None))
        self.tableWidgetNetworkCharacteristics.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("MainWindow", "Nodes Characteristics", None))
        self.pushButtonDegreeCentrality.setText(_translate("MainWindow", "Degree Centrality", None))
        self.pushButtonBetweennessCentrality.setText(_translate("MainWindow", "Betweenness Centrality", None))
        self.pushButtonClosenessCentrality.setText(_translate("MainWindow", "Closeness Centrality", None))
        self.pushButtonEigenvCentrality.setText(_translate("MainWindow", "Eigenvector Centrality", None))
        self.groupBoxNetworkGenerator.setTitle(_translate("MainWindow", "Network Generator", None))
        self.label.setText(_translate("MainWindow", "Network Type:", None))
        self.labelConfigureParameters.setText(_translate("MainWindow", "Please Configure Parameter (s)", None))
        item = self.tableWidgetParameter.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        self.pushButtonGenerateNetwork.setText(_translate("MainWindow", "Generate Network", None))
        self.checkBoxEdge.setText(_translate("MainWindow", "Show Edge", None))
        self.pushButtonRestNetwork.setText(_translate("MainWindow", "Reset Network", None))
        self.groupBoxBaseMap.setTitle(_translate("MainWindow", "Base Map", None))
        self.pushButtonSelectBaseMap.setText(_translate("MainWindow", "Select", None))
        self.pushButtonViewBaseMap.setText(_translate("MainWindow", "View", None))
        self.labelSelectBaseMap.setText(_translate("MainWindow", "Please Select Base Map File", None))
        self.groupBoxFindParameters.setTitle(_translate("MainWindow", "Find Parameters", None))
        self.label_2.setText(_translate("MainWindow", "Early adopters:", None))
        self.label_3.setText(_translate("MainWindow", "p-op-leader", None))
        self.label_4.setText(_translate("MainWindow", "p-adoption", None))
        self.label_pleader_value.setText(_translate("MainWindow", "0.000", None))
        self.label_padopter_value.setText(_translate("MainWindow", "0.000", None))
        self.pushButtonFindParameters.setText(_translate("MainWindow", "Find Parameters", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Error Counter Map", None))
        self.label_6.setText(_translate("MainWindow", "Map Title：", None))
        self.label_5.setText(_translate("MainWindow", "Parameter file：", None))
        self.pushButtonOpenParameter.setText(_translate("MainWindow", "Open", None))
        self.pushButtonDrawCounterMap.setText(_translate("MainWindow", "View", None))
        self.groupBoxSimulator.setTitle(_translate("MainWindow", "Information Diffusion", None))
        self.groupBoxLTModel.setTitle(_translate("MainWindow", "Linear Threshold Model", None))
        self.labelThreshold.setText(_translate("MainWindow", "Threshold:", None))
        self.lineEditThreshold.setToolTip(_translate("MainWindow", "Please input a number between 0 and 1.", None))
        self.groupBoxSeedNodes.setTitle(_translate("MainWindow", "Seed Nodes", None))
        self.labelNumberofSeeds.setText(_translate("MainWindow", "Number:", None))
        self.labelSelectSeedsAlgorithm.setText(_translate("MainWindow", "Algorithm :", None))
        self.lineEditNumberofSeedNodes.setToolTip(_translate("MainWindow", "Please input an integer.", None))
        self.pushButtonGenerateSeedNodes.setText(_translate("MainWindow", "Generate Seed Nodes", None))
        self.groupBoxICModel.setTitle(_translate("MainWindow", "Independent Cascade Model", None))
        self.labelOpinionNodePogagate.setText(_translate("MainWindow", "Popagate Probability(Opinion Node )", None))
        self.lineEditOpinionNodePopagate.setToolTip(_translate("MainWindow", "Please input a number between 0 and 1.", None))
        self.lineEditOpinionNodePopagate.setText(_translate("MainWindow", "0.3", None))
        self.labelNormalNodePopagate.setText(_translate("MainWindow", "Popagate Probability(Normal Node)", None))
        self.lineEditNormalNodePopagate.setToolTip(_translate("MainWindow", "Please input a number between 0 and 1.", None))
        self.lineEditNormalNodePopagate.setText(_translate("MainWindow", "0.2", None))
        self.pushButtonDiffusion.setText(_translate("MainWindow", "Information Difussion", None))
        self.groupBoxOpinionLeaders.setTitle(_translate("MainWindow", "Opinion Leaders", None))
        self.radioButtonWholeNetwork.setText(_translate("MainWindow", "Whole Network", None))
        self.radioButtonEachCommunity.setText(_translate("MainWindow", "Each Community", None))
        self.label_8.setText(_translate("MainWindow", "Proportion：", None))
        self.label_7.setText(_translate("MainWindow", "%", None))
        self.pushButtonGenerateOpinionLeaders.setText(_translate("MainWindow", "Generate Opinion Leaders", None))
        self.groupBoxComplexNetwork.setTitle(_translate("MainWindow", "Complex Network Generator", None))
        item = self.tableWidgetComplexLinks.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NetID[S]", None))
        item = self.tableWidgetComplexLinks.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "#Node[S]", None))
        item = self.tableWidgetComplexLinks.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rule[S]", None))
        item = self.tableWidgetComplexLinks.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "NetID[D]", None))
        item = self.tableWidgetComplexLinks.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "#Node[D]", None))
        item = self.tableWidgetComplexLinks.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Rule[D]", None))
        self.pushButtonOKforNetworkCount.setText(_translate("MainWindow", "OK", None))
        self.labelNetworkCount.setText(_translate("MainWindow", "The number of simple networks:", None))
        self.groupBoxEverySimpleNetwork.setTitle(_translate("MainWindow", "Single Network Setting", None))
        self.labelNetworkID.setText(_translate("MainWindow", "NetworkID:", None))
        self.labelNetworkTypeSingle.setText(_translate("MainWindow", "NetworkType:", None))
        item = self.tableWidgetParameterComplexParameters.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value", None))
        self.pushButtonOverview.setText(_translate("MainWindow", "Overview of all parameters", None))
        self.pushButtonSaveComplexNetworkParams.setText(_translate("MainWindow", "Save the above parameters", None))
        self.labelNetworkCount_2.setText(_translate("MainWindow", "Connect networks:", None))
        self.pushButtonExpandShrink.setText(_translate("MainWindow", "Expand Table", None))
        self.groupBoxBaseMapComplex.setTitle(_translate("MainWindow", "Base Map", None))
        self.pushButtonSelectBaseMapComplex.setText(_translate("MainWindow", "Select", None))
        self.pushButtonViewBaseMapComplex.setText(_translate("MainWindow", "View", None))
        self.labelSelectBaseMapComplex.setText(_translate("MainWindow", "Please Select Base Map File", None))
        self.pushButtonRemoveConnect.setText(_translate("MainWindow", "RemoveConnect", None))
        self.pushButtonAddConnect.setText(_translate("MainWindow", "AddConnect", None))
        self.pushButtonGenerateComplexNetwork.setText(_translate("MainWindow", "Generate Complex Network", None))
        self.groupBoxCommunity.setTitle(_translate("MainWindow", "Community", None))
        item = self.tableWidgetCommunity.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "# Nodes", None))
        item = self.tableWidgetCommunity.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Color", None))
        self.label_9.setText(_translate("MainWindow", "Community", None))
        self.groupBoxPreview.setTitle(_translate("MainWindow", "Preview", None))
        self.menuNetwork.setTitle(_translate("MainWindow", "Network", None))
        self.menuAnalysis.setTitle(_translate("MainWindow", "Analysis", None))
        self.menuSimulator.setTitle(_translate("MainWindow", "Simulator", None))
        self.menuCommunity.setTitle(_translate("MainWindow", "Community", None))
        self.menuData.setTitle(_translate("MainWindow", "Data", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))
        self.actionSave_As.setText(_translate("MainWindow", "Save As", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionFindParameters.setText(_translate("MainWindow", "FindParameters", None))
        self.actionDemonstrate_Temporal_Spatial_Process.setText(_translate("MainWindow", "Demonstrate Temporal-Spatial Process", None))
        self.actionGeoDataFromTweets.setText(_translate("MainWindow", "GeoDataFromTweets", None))
        self.actionSocialNetworkFromTweets.setText(_translate("MainWindow", "Extract Diffusion Network", None))
        self.actionGenerate_Simulated_Network.setText(_translate("MainWindow", "Generate Single Simulated Network", None))
        self.actionNetwork_Analysis.setText(_translate("MainWindow", "Network Analysis", None))
        self.actionWindowNetwork_Analysis.setText(_translate("MainWindow", "Network Analysis", None))
        self.actionWindowNetwork_Generator.setText(_translate("MainWindow", "Network Generator", None))
        self.actionWindowSimulating_Information_Diffusion.setText(_translate("MainWindow", "Simulating Information Diffusion", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionDocument.setText(_translate("MainWindow", "Document", None))
        self.actionGenerate_Complex_Network.setText(_translate("MainWindow", "Generate Complex Simulated Network", None))
        self.actionCNM.setText(_translate("MainWindow", "CNM", None))
        self.actionGirvanNewman.setText(_translate("MainWindow", "GirvanNewman", None))
        self.actionOSLOM.setText(_translate("MainWindow", "OSLOM", None))
        self.actionCollect_tweets_by_Account.setText(_translate("MainWindow", "Collect tweets by Account", None))
        self.actionExtract_Social_Network.setText(_translate("MainWindow", "Extract Social Network", None))
        self.actionMerge_Network.setText(_translate("MainWindow", "Merge Network", None))
        self.actionPredict_Diffusion.setText(_translate("MainWindow", "Predict Diffusion", None))
        self.actionLoad_Network.setText(_translate("MainWindow", "Load Network", None))
        self.actionInformation_Diffusion_City.setText(_translate("MainWindow", "Information Diffusion [City]", None))
        self.actionUser.setText(_translate("MainWindow", "User", None))
        self.actionCity.setText(_translate("MainWindow", "City", None))
        self.menuInformation_Diffusion_City.setText(_translate("MainWindow", "[City]Information Diffusion", None))
        self.actionExtract_Diffusion_Network.setText(_translate("MainWindow", "Extract Diffusion Network", None))
        self.actionExtract_Mentioned_Network.setText(_translate("MainWindow", "Extract Mentioned Network", None))
        self.actionCompute_Weight_Matrix.setText(_translate("MainWindow", "Compute Weight Matrix", None))
        self.actionSave_Network.setText(_translate("MainWindow", "Save Network", None))
        self.menuInformation_Diffusion_User_2.setText(_translate("MainWindow", "[User]Information Diffusion", None))
        self.actionUser_Level.setText(_translate("MainWindow", "User Level", None))
        self.actionCity_Level.setText(_translate("MainWindow", "City Level", None))
        self.actionUser_Manual.setText(_translate("MainWindow", "User Manual", None))
        self.actionAbout_2.setText(_translate("MainWindow", "About", None))

